#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Tool to merge PNGs obtained by the GoFullPAge plugin (scan unsavable online pdf readers),
extract each page, merge into a pdf, and compress it

@author: laurent90git
"""
from tqdm import tqdm
import matplotlib.image
import matplotlib.pyplot as plt
import numpy as np
import glob
import os

#%% THINGS THAT YOU NEED TO MODIFY
#######################################
# Provide list of chapters (each one is a list of the associated PNGs generated by the browser addon)
# Make sure the list of PNGS and of chapters is in the correct order !
chapters = []
for ichap in range(0,10):
  name = f"chap{ichap}"
  chapters.append( sorted(glob.glob(f"/my/folder/fullscreen_captures/chap{ichap}*.png")) )
  # TODO: deal with issues with name sorting if more than 10 images...

## what color to use to identify page bounds ?
split_color = np.array([0.855, 0.855, 0.886, 1]) # color which is associated with page breaks (gap between pages)
split_threshold = 1e-4 # tune if required to properly detect page bounds in the image

## what lateral trim to apply to remove unnecessary elements from the original screenshot
trim_lateral= [68+45, 1920-68-50+5] # TODO: detemrine automatically
#######################################

temp_dir = "temp_pages" # directory to use to process indivual pages

os.system(f"rm -r {temp_dir}")
os.system(f"mkdir {temp_dir}")

#%% process chapter by chapter
for ichap in range(len(chapters)):
  print(f"\nchapter {ichap+1}/{len(chapters)}")
  
  # read the associated images
  imgs = []
  for file in chapters[ichap]:
    imgs.append( plt.imread(file) )
  
  img_global = np.vstack(imgs)
   
  
  page_width = trim_lateral[1]-trim_lateral[0]
  img_global=img_global[:,trim_lateral[0]:trim_lateral[1],:]
  
  # go trough the image vertically, top to bottom, to identiy page breaks
  ny = img_global.shape[0]
  i = 0
  Isplit = []
  for i in tqdm(range(ny)):  # find first separation
    indicator = 0
    for j in range(split_color.size):
      indicator += np.linalg.norm( img_global[i,:,j] - split_color[j])**2
    indicator = indicator / (split_color.size * img_global.shape[1]) # scale by pixel and color size
    
    if indicator < split_threshold:
      Isplit.append(i)
    
  Isplit.append(img_global.shape[0]-1) # add the last pixel line
  
  # Properly detect blocks of thresholded pixel lines
  page_bounds = []  
  for i in range(1,len(Isplit)):
    if Isplit[i]==Isplit[i-1]+1: # contiguous:
      pass
    else:
      page_bounds.append(Isplit[i-1])
      page_bounds.append(Isplit[i])
  
  tmp = np.mean(np.diff(page_bounds))
  pages = []
  for i in range(len(page_bounds)-1):
    if (page_bounds[i+1]-page_bounds[i]) >= 0.9*tmp: # to dissociate interpage areas that need to be removed
      pages.append([page_bounds[i], page_bounds[i+1]])
        
  page_heights = np.array([p[1]-p[0] for p in pages])
  assert np.allclose(page_heights, np.min(page_heights), rtol=1e-1), "pages are of different sizes" # allow small issue
  assert(abs(pages[-1][-1] - img_global.shape[0]) < np.mean(page_heights)), "last page issue"
  
  max_page_height = np.max( page_heights )
  
  # Extract images and save as pngs
  for i in tqdm(range(len(pages))):
    current_image = img_global[pages[i][0]:pages[i][1]]
    # add whitespace is nto tall enough:
    if page_heights[i] < max_page_height:
      print(f"adding whitespace to image {i}, matching maximum page height")
      white = np.ones(( max_page_height - page_heights[i], page_width, 4))
      current_image = np.vstack((current_image, white))
      
    matplotlib.image.imsave(f'{temp_dir}/{ichap}_{i:04d}.png', current_image)
  
#%% Combine them
print('Building PDF...')
os.system(f"convert -append {temp_dir}/*.png output_raw.pdf")

#%% Add OCR and compress
print('Adding OCR and compressing...')
os.system("ocrmypdf --optimize 3 output_raw.pdf  output.pdf")
print('done !')
